# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amarzana <amarzana@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/06 21:33:29 by amarzana          #+#    #+#              #
#    Updated: 2022/03/06 22:43:56 by amarzana         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
SRC = main.c generate_dict.c atoi.c


$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)

.PHONY: fclean

fclean:
	rm -f $(NAME)

